import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import { FaCarAlt } from "react-icons/fa";
import CustomerActions from "@/components/customer/customer-actions";
import * as React from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
          <div className="flex items-center justify-between h-full my-2 mx-5">
              <div className="flex items-center gap-x-1.5">
                  <FaCarAlt className="text-emerald-800 w-6 h-6" />
                  <h2 className="font-extrabold text-2xl text-emerald-500">Suvaroglu</h2>
              </div>

              <CustomerActions />
          </div>
        {children}
      </body>
    </html>
  );
}
